### ISSUE TITLE
cocos creator 构建vivo小游戏报错

### ISSUE THREAD

**Issue by 415848878** [vivominigame/issues#150]
引擎版本2.2.2
报错信息

Build Failed: Error: 小游戏依赖的npm包安装失败！错误：
    at EventEmitter.<anonymous> (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/main/ipc.js:1:4952)
    at EventEmitter.emit (events.js:194:13)
    at EventEmitter.emit (domain.js:469:20)
    at Object.i.reply (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/main/ipc.js:1:2117)
    at /Applications/CocosCreator.app/Contents/Resources/builtin/vivo-runtime/build-runtime.js:440:27
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:194:13)
    at ChildProcess.EventEmitter.emit (domain.js:469:20)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
	--------------------
    at /Applications/CocosCreator.app/Contents/Resources/builtin/vivo-runtime/build-runtime.js:440:33
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:194:13)
    at ChildProcess.EventEmitter.emit (domain.js:469:20)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/lib/builder/index.js:1:3815
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52:16
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:1209:30
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/lib/builder/index.js:1:806
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by jesseband** [comment]
升级下版本，到2.3.0试试
脚手架可能没安装好
要选择导出vivo游戏
参考 https://minigame.vivo.com.cn/documents/#/lesson/?id=%e5%a6%82%e4%bd%95%e8%b0%83%e8%af%95
