### ISSUE TITLE
rpk包 莫名出现闪退情况 h5 微信平台不曾出现

### ISSUE THREAD

**Issue by LiuYuNan01** [vivominigame/issues#224]
平台版本号 1084
最低版本号 1083

已经卡主2天了  有人遇到过这种情况吗
 
![5ba962a0fb5c1cdc0f8e750146ae90f](https://user-images.githubusercontent.com/39432647/106377673-968fed80-63d9-11eb-8bb5-149db984955c.jpg)
 
![e0146394a1b1c0b40b5ad5d96249e09](https://user-images.githubusercontent.com/39432647/106377681-a576a000-63d9-11eb-8913-78fe7a6c18b4.png)

**Comment by LiuYuNan01** [comment]
java.lang.RuntimeException: (see stack)Uncaught Error: TypeError: Cannot read property 'length' of null[0]t.fireTimeout@(no filename):8&anonymous@(no filename):8&& at com.vivo.hybrid.game.jsruntime.n.b(SourceFile:51)& at com.vivo.hybrid.game.jsruntime.n.a(SourceFile:41)& at com.vivo.hybrid.game.jsruntime.GameRuntime.javaScriptExceptionCallback(SourceFile:736)& at org.cocos2dx.lib.Cocos2dxRenderer.nativeRender(Native Method)& at com.vivo.hybrid.game.render.GameRender.onDrawFrame(SourceFile:166)& at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)& at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)




java.lang.RuntimeException: (see stack)Uncaught Error: TypeError: Cannot read property 'getComponent' of null[0]t.fireTimeout@(no filename):8&anonymous@(no filename):8&& at com.vivo.hybrid.game.jsruntime.n.b(SourceFile:51)& at com.vivo.hybrid.game.jsruntime.n.a(SourceFile:41)& at com.vivo.hybrid.game.jsruntime.GameRuntime.javaScriptExceptionCallback(SourceFile:736)& at org.cocos2dx.lib.Cocos2dxRenderer.nativeRender(Native Method)& at com.vivo.hybrid.game.render.GameRender.onDrawFrame(SourceFile:152)& at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)& at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)






每个版本都会有几率出现

**Comment by LiuYuNan01** [comment]
10830510 引擎版本最严重 崩溃率百分之20

**Comment by LiuYuNan01** [comment]
后台的数据显示崩溃率很高, 

但是自己重来没有遇到 ...........................  难受阿 怎么办  有人遇到吗

**Comment by LiuYuNan01** [comment]
有玩家反馈 vivo弹出页面 : 对不起,游戏好像出了点问题
