### ISSUE TITLE
微信小游戏一键转换vivo工程问题沟通

### ISSUE THREAD

**Issue by yuebai008** [vivominigame/issues#256]
### 反馈内容：
1、包名名称
2、问题截图
3、转换后的vivo工程压缩包
4、通讯方式，可联系vivo商务反馈微信转换问题，可直接qq在线沟通

#### 若有对微信一键转换测试验证有兴趣的，可以参考该文档：https://minigame.vivo.com.cn/documents/#/lesson/base/wx_transfer
有问题可以及时反馈沟通

**Comment by ucchen** [comment]
cocoscreator 3.8.2 微信空工程，使用转换工具，转换出来的工程启动失败。

**Comment by yuebai008** [comment]
> cocoscreator 3.8.2 微信空工程，使用转换工具，转换出来的工程启动失败。

能发一下包 我看下嘛

**Comment by ucchen** [comment]
你好，只要用cocos3.8.2创建一个空工程就可以复现，问题出在require("./".concat(js))这里，找不到对应的js文件。
可以加QQ聊吗？QQ：278805866

**Comment by yuebai008** [comment]
脚手架1.23.3已修复该问题

//使用npm官方源，可以快速拉取最新代码
npm config set registry https://registry.npmjs.org
npm i -g @vivo-minigame/cli

**Comment by yujuanyixiansheng** [comment]
unity打包成微信小游戏，里面删除了sdk相关代码，转成vivo包以后重新加入sdk代码会报错，报错如下，能帮忙看看吗？


(no filename):8 [PLUGIN ERROR]  FileSystem_statSyncCatch: internal://files  Cannot read property 'javaObject' of undefined TypeError: Cannot read property 'javaObject' of undefined
    at statSync ((no filename):8:90893)
    at e.value (unity_plugin_1.2.32.js:2:1)
    at e.<anonymous> (unity_plugin_1.2.32.js:2:1)
    at s (regeneratorRuntime.js:47:1)
    at Generator.<anonymous> (regeneratorRuntime.js:135:1)
    at Generator.next (regeneratorRuntime.js:76:1)
    at unity_plugin_1.2.32.js:2:1
    at new Promise (<anonymous>)
    at gn (unity_plugin_1.2.32.js:2:1)
    at e.value (unity_plugin_1.2.32.js:2:1)

**Comment by yuebai008** [comment]
> unity打包成微信小游戏，里面删除了sdk相关代码，转成vivo包以后重新加入sdk代码会报错，报错如下，能帮忙看看吗？
> 
> (no filename):8 [PLUGIN ERROR] FileSystem_statSyncCatch: internal://files Cannot read property 'javaObject' of undefined TypeError: Cannot read property 'javaObject' of undefined at statSync ((no filename):8:90893) at e.value (unity_plugin_1.2.32.js:2:1) at e. (unity_plugin_1.2.32.js:2:1) at s (regeneratorRuntime.js:47:1) at Generator. (regeneratorRuntime.js:135:1) at Generator.next (regeneratorRuntime.js:76:1) at unity_plugin_1.2.32.js:2:1 at new Promise () at gn (unity_plugin_1.2.32.js:2:1) at e.value (unity_plugin_1.2.32.js:2:1)

rpk能发一下看下嘛

**Comment by yujuanyixiansheng** [comment]
github上不支持上传rpk文件

**Comment by yuebai008** [comment]
> github上不支持上传rpk文件

加下企业微信 
![image](https://github.com/user-attachments/assets/c1349281-9006-4c9a-9657-2d01f476dadb)

**Comment by yujuanyixiansheng** [comment]
加你了，麻烦通过一下哟，谢谢
