### ISSUE TITLE
Uncaught TypeError: Cannot create property 'state' on number '-1'[0]cc.audioEngine.resumeMusic

### ISSUE THREAD

**Issue by jesseband** [vivominigame/issues#7]
vivo-jesse  10:33:20
版本2.1.3，cc.audioEngine.resumeMusic存在，运行会卡到这个地方，
真机调试报错信息：
java.lang.RuntimeException: (see stack)Uncaught TypeError: Cannot create property 'state' on number '-1'[0]cc.audioEngine.resumeMusic@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/jsb-adapter/engine/index.js:267
[1]updateSetting@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
[2]handlerLoginSuccess@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
[3]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
[4]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
[5]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
[6]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
[7]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.szydhw.hcrdqq.vivominigame/src/project.js:1
at com.vivo.hybrid.game.jsruntime.GameRuntime$3.run(SourceFile:552)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7076)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by jesseband** [comment]
解决方案 ：替换下 vivo-runtime插件里的 jsb-audio.js 试下，把方法调整到了 if 里面
