### ISSUE TITLE
laya2.3版本 readFile报错问题

### ISSUE THREAD

**Issue by jesseband** [vivominigame/issues#8]
HybridGame.AbstractHybridFeature: Fail to invoke: readFile
    java.nio.charset.IllegalCharsetNameException: 
        at java.nio.charset.Charset.checkCharsetName(Charset.java:194)
        at java.nio.charset.Charset.forName(Charset.java:295)
        at com.vivo.hybrid.common.g.g.a(SourceFile:203)
        at com.vivo.hybrid.game.feature.storage.file.FileStorage.readText(SourceFile:411)
        at com.vivo.hybrid.game.feature.storage.file.GameFileStorageFeature.doReadText(SourceFile:364)
        at com.vivo.hybrid.game.feature.storage.file.GameFileStorageFeature.doReadDispatch(SourceFile:320)
        at com.vivo.hybrid.game.feature.storage.file.GameFileStorageFeature.invokeInner(SourceFile:101)
        at com.vivo.hybrid.game.runtime.hapjs.bridge.AbstractHybridFeature.invoke(SourceFile:108)
        at com.vivo.hybrid.game.jsruntime.h$a.run(SourceFile:191)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by jesseband** [comment]
解决方案 https://ask.layabox.com/question/44015
